### ISSUE TITLE
Unpredictable results when using fetchMultipleRates

### ISSUE THREAD

**Issue by batjko** [tajawal/swap#1]
Hi there,

Lovely little package, thanks for publishing it!

I just took it for a whirl and found that it returns various numbers of results, including sometimes nothing:

![image](https://cloud.githubusercontent.com/assets/7287076/13157268/cfce1ee8-d67e-11e5-82ba-8e14cbfbfcb0.png)

Is there some kind of timeout exiting too soon perhaps?

Cheers

**Comment by khurrumqureshi** [comment]
@batjko thanks for the feedback.

Yes there is a timeout of 2000ms if provider does not respond within this time limit that provider get skipped from the result set.

In your particular case you will get result from maximum two providers yahoo and finance because European central bank only supports EUR as base currency and open exchange rates requires appId.

**Comment by batjko** [comment]
Ok that makes sense.
Could we get an option to specify the timeout as a parameter by any chance?
Given that it's asynchronously retrieved, I may want to give it more time...

**Comment by meabed** [comment]
@batjko sure we missed that out. will be added.

**Comment by batjko** [comment]
:+1:

**Comment by meabed** [comment]
Fixed, 

```
// Add the yahoo finance provider
var provider = new swap.providers.YahooFinance();
// request timeout provider
provider.setRequestOptions({timeout: 10000});
```

**Comment by batjko** [comment]
Excellent, thank you!
